daytimetcpcli:
	mkdir -p ../release
	g++ -g -std=c++11 -o ../release/daytimetcpcli daytimetcpcli.cc
	../release/daytimetcpcli 206.168.112.96

daytimetcpsrv:
	mkdir -p ../release
	g++ -g -std=c++11 -o ../release/daytimetcpsrv daytimetcpsrv.cc
	../release/daytimetcpsrv

